song_list_arcaea = [
    '#1f1e33',
    '[X]',
    '0xe0e1ccull',
    '1F√',
    '7thSense', 
    '99 Glooms',
    'A Wandering Melody of Love',
    'Abstruse Dilemma',
    'Aegleseeker',
    'Ai Drew',
    'AI[UE]OON',
    'Alexandrite'
    'Alice à la mode',
    'Alice\'s Suitcase',
    'Altair (feat. *spiLa*)',
    'Altale',
    'AlterAle',
    'AMAZING MIGHTYYYY!!!!',
    'amygdata',
    'Anökumene',
    'Antagonism',
    'Antithese',
    'April showers',
    'Arcahv',
    'Arcana Eden',
    'Ascent',
    'Astra walkthrough',
    'Astral tale',
    'AttraqtiA',
    'Aurgelmir',
    'Auxesia',
    'Avant Raze',
    'Ävril -Flicka i krans-',
    'Axium Crisis',
    'Babaroque',
    'BADTEK',
    'Bamboo',
    'BATTLE NO.1',
    'Be There',
    'Beside You',
    'Black Lotus',
    'Black Territory',
    'Blaster',
    'Blocked Library',
    'Blossoms',
    'BLRINK',
    'blue comet',
    'Blue Rose',
    'Bookmaker (2D Version)',
    'BUCHiGiRE Berserker',
    'Bullet Waiting for Me (James Landino remix)',
    'Call My Name feat. Yukacco',
    'Callima Karma',
    'Can I Friend You on Bassbook? Lol',
    'Capella',
    'carmine,scythe',
    'CHAOS',
    'Chelsea',
    'Chronicle',
    'Chronostasis',
    'Climax',
    'Clotho and the stargazer',
    'Coastal Highway',
    'cocoro*cosmetic',
    'conflict',
    'corps-sans-organes',
    'Corruption',
    'Cosmica',
    'Cosmo Pop Funclub',
    'Crimson Throne',
    'CROSS†OVER',
    'CROSS†SOUL',
    'cry of viyella',
    'Crystal Gravity',
    'Cyaegha',
    'cyanine',
    'Cybernecia Catharsis',
    'CYCLES',
    'Dancin\' on a Cat\'s Paw',
    'Dandelion',
    'Dantalion',
    'DataErr0r',
    'Dazzle hop',
    'Defection',
    'Dement ~after legend~',
    'Devillic Sphere',
    'Dialnote',
    'Diode',
    'Divine Light of Myraid',
    'Dot to Dot feat. shully',
    'Dreadnought',
    'Dream goes on',
    'Dreamin\' Attraction!!',
    'DRG',
    'dropdead',
    'DX Choseinou Full Metal Shojo',
    'Eccentric Tale',
    'Einherjar Joker',
    'Empire of Winter',
    'enchanted love',
    'ENERGY SYNERGY MATRIX',
    'Equilibrium',
    'Essence of Twilight',
    'Ether Strike',
    'Evening in Scarlet',
    'Evoltex (poppi\'n mix)',
    'Faint Light (Arcaea Edit)',
    'Fairytale',
    'Fallensquare',
    'False Embellishment',
    'Far Away Light',
    'Feels So Right feat. Renko',
    'Felis',
    'Filament',
    'Final Step!',
    'First Snow',
    'Flashback',
    'FLUFFY FLASH',
    'Flyburg and Endroll',
    'Fracture Ray',
    'Free Myself',
    'FREEF4LL',
    'Gengaozo',
    'Galactic Love',
    'Galaxy Friends',
    'Garakuta Doll Play',
    'Gekka (Short Version)',
    'Genesis',
    'GENOCIDER',
    'GIMME DA BLOOD',
    'GIMMICK',
    'Give Me a Nightmare',
    'GLORY：ROAD',
    'Glow',
    'goldenslaughterer',
    'Good-bye, Merry-Go-Round.',
    'GOODTEK (Arcaea Edit)',
    'Got hive of Ra',
    'Grevious Lady',
    'Grimheart',
    'Halcyon',
    'Hall of Mirrors',
    'Harutopia ~Utopia of Spring~',
    'Haze of Autumn',
    'Head BONK ache',
    'Heart',
    'Heart Jackin\'',
    'Heavenly caress',
    'Heavensdoor',
    'Hiiro Gekka, Kyoushou no Zetsu (nayuta 2017 ver.)',
    'Hikari',
    'HIVEMIND',
    'Hybris (The one who shattered)',
    'I\'ve heard it said',
    'Iconoclast',
    'Ignotus',
    'Ignotus Afterburn',
    'II',
    'Ikazuchi',
    'Illegal Paradise',
    'IMPACT',
    'Impure Bird',
    'Infinite Strife,',
    'Infinity Heaven',
    'init()',
    'inkar-usi',
    'INTERNET OVERDOSE',
    'INTERNET YAMERO',
    'IZANA',
    'Jump',
    'Kanagawa Cyber Culvert',
    'Kissing Lucifer',
    'LAMIA',
    'Lapis',
    'La\'qryma of the Wasteland',
    'Last',
    'Last | Eternity',
    'Last | Moment',
    'Last Celebration',
    'lastendcondunter',
    'Lawless Point',
    'Lazy Addiction',
    'Let you DIVE! (nitro rmx)',
    'Lethaeus',
    'Let\'s Rock (Arcaea mix)',
    'Libertas',
    'Life is PIANO',
    'Lightning Screw',
    'Lights of Muse',
    'Linear Accelerator',
    'Live Fast Die Young',
    'Löschen',
    'Lost Civilization',
    'Lost Desire',
    'Lost Emotion feat. nomico',
    'Lost in the Abyss',
    'Loveless Dress',
    'Lucid Traveler',
    'Lucifer',
    'Lumia',
    'LunarOrbit -believe in the Espebranch road-',
    'Macrocosmic Modulation',
    'Magnolia',
    'MAHOROBA',
    'Malicious Mischance',
    'Manic Jeer',
    'MANTIS (Arcaea Ultra-Bloodrush VIP)',
    'MAXRAGE',
    'Maze No.9',
    'Mazy Metroplex',
    'Medusa',
    'Memory Forest',
    'memoryfactory.lzh',
    'MERLIN',
    'Metallic Punisher',
    'Mirzam',
    'Misdeed -la bonté de Dieu et l\'origine du mal-',
    'Mistempered Malignance'
    'Modelista',
    'Monochrome Princess',
    'Moonheart',
    'NEO WINGS',
    'New York Back Raise',
    'next to you',
    'Nhelv',
    'Nirv lucE',
    'NULCTRL',
    'NULL APOPHENIA',
    'nέο κόsmo',
    'Oblivia',
    'OMAKENO Stroke',
    'Oracle',
    'Oshama Scramble!',
    'ouroboros-twin stroke of the end-',
    'overdead.',
    'Overwhelm',
    'OΔYΣΣEIA',
    'Paper Witch'
    'Paradise',
    'Particle Arts',
    'Party Vinyl',
    'Pentiment',
    'Phantasia',
    'PICO-Pico-Translation!',
    'PRAGMATISM',
    'PRAGMATISM -RESURRECTION-',
    'PRIMITIVE LIGHTS',
    'Prism',
    'Protoflicker',
    'PUPA',
    'Purgatorium',
    'Purple Verse',
    'qualia -ideaesthesia-',
    'Quon',
    'Rabbit In The Black Room',
    'Raven\'s Pride',
    'REconstruction',
    'Red and Blue',
    'Red and Blue and Green',
    'Redolent Shape',
    'Redraw the Colorless World',
    'Reinvent'
    'REKKA RESONANCE',
    'Relentless',
    'ReviXy',
    'RGB',
    'Ringed Genesis',
    'Rise',
    'Rise of the World',
    'Romance Wars',
    'Rugie',
    'SACRIFICE feat. ayame',
    'SAIKYO STRONGER',
    'Sakura Fubuki',
    'san skia',
    'Sayonara Hatsukoi'
    'Scarlet Cage',
    'Scarlet Lance',
    'Seclusion',
    'Senkyou',
    'Shades of Light in a Transcendent Realm',
    'Sherriruth',
    'Sherriruth (Laur Remix)',
    'Silent Rush'
    'Singularity',
    'Singularity VVVIP',
    'Small Cloud Suger Candy',
    'Snow White',
    'Solitary Dream',
    'SOUNDWiTCH',
    'Specta',
    'Spider\'s Thread',
    'STAGER (ALL STAGE CLEAR)',
    'Stasis',
    'Strongholds',
    'Sulfur',
    'Summer Fireworks of Love',
    'Suomi',
    'SUPERNOVA',
    'Surrender',
    'Syro',
    'syūten',
    'Tempestissimo',
    'TEmPTaTiON',
    'Teriqma',
    'Testify',
    'The Message',
    'The Survivor (Game Edit)',
    'THE ULTIMACY',
    'Tie me down gently'
    'Tiferet',
    'To the Milky Way',
    'To, Alice Liddell',
    'Trap Crow',
    'trappola bewitching',
    'Trrricksters!!',
    'Tsuki ni Murakumo, Hana ni Kaze',
    'Turbocharger',
    'Ultimate taste',
    'UNKNOWN LEVELS',
    'Used to Be',
    'Valhalla:0',
    'Vandalism',
    'VECTOЯ',
    'Vexaria',
    'Vicious Heroism',
    'Vindication',
    'Vivid Theory',
    'Viyella\'s Tears',
    'WAIT FOR DAWN',
    'with U',
    'World Ender',
    'World Fragments III(radio edit)',
    'World Vanquisher',
    'world.execute(me);',
    'Xanatos',
    'Xeraphinite',
    'Yosakura Fubuki',
    'Your voice so... feat. Such',
    'αterlβus',
    'γuarδina',
    'μ',
    'ω4']

song_list_phigros = [
    '996',
    '[PRAW]',
    '+ERABY+E CONNEC+10N',
    'Ad astra per aspera',
    'After Dawn',
    'Aleph-0',
    'Another Me',
    'Another Round',
    'Aphasia',
    'Apocalypse',
    'Apocalyptic',
    'Ark',
    '-Arkhei-',
    'Äventyr',
    'Better Graphic Animation',
    'Bonus Time',
    'Bougainvillea',
    'Brave Notes',
    'Break Over',
    'Break Through The Barrier',
    'Burn',
    'c.s.q.n.',
    'Cereris',
    'Cervelle Connexion',
    'Chronologika',
    'Chronomia',
    'Chronos Collapse - La Campanella',
    #'Chronostasis',
    'Cipher : /2&//<|0',
    'Class Memories',
    'Clock Paradox',
    'Colorful Days♪',
    'Compute It With Some Devilish Alcoholic Steampunk Engines',
    'Concvssion',
    'Crave Wave',
    'Credits',
    'CROSS†SOUL',
    'cryout',
    'Cthugha',
    'Dance with Silence',
    'Dash',
    'DataErr0r',
    'dB doll',
    'Dead Soul',
    'Demokin',
    'Demuirge',
    'Disorder',
    'Disorted Fate',
    'Dlyrotz',
    'Don\'t Never Around',
    'Doppelganger',
    'Dreamland',
    'Drop it',
    'El Condor Pasa (Phigros Edit)',
    'El último baile',
    'Electron',
    'End Me',
    'ENERGY SYNERGY MATRIX',
    'Energy trixxx',
    'Engine x Start!! (melody mix)',
    'Eradication Catastrophe',
    'Eternal Snow',
    'Etlaw',
    'Final Step!',
    'Find_Me',
    'FULi AUTO BUSTER',
    'FULi AUTO SHOOTER',
    'Future Mind',
    'Get Back',
    'Get Ready!!',
    'Glaciaxion',
    'GOODBOUNCE',
    'GOODFORTUNE',
    'GOODRAGE',
    'GOODTEK',
    'GOODWORLD',
    'Hardcore Kwaya',
    'HAZARD',
    'Horizon Blue',
    'HumaN',
    'I Must Say No',
    'Igallta',
    'inferior',
    'INFiNiTE ENERZY -Overdose-',
    #'Infinity Heaven',
    'Initialize',
    'JunXion Between Life And Death(VIP Mix)',
    'Kerberos',
    'Khronostasis Katharsis',
    'Labyrinth in Kowloon: Walled World',
    'Leave All Behind',
    'life flashes before weeb eyes',
    'Luminescence',
    'Luminescent',
    'Magenta Potion',
    'MARENOL',
    'mechanted',
    'micro.wav',
    'Miracle Forest(VIP Mix)',
    'MOBILYS',
    'modulus',
    'Next Time',
    #'Nhelv',
    'Nick of Time',
    'NO ONE YES MAN',
    'Non-Melodic Ragez (MUG Edit)',
    'Now Is The Time, Do It',
    'NYA!!!(Phigros ver.)',
    'On And On!!',
    'opia',
    'Orthodox',
    'Palescreen',
    'Parallel Retrogression(Game Ver.)',
    'Pixel Rebelz',
    'Poison AND÷OR Affection',
    'Pont des souvenirs',
    #'Protoflicker',
    'Rainy Heart',
    'Rainy Season',
    'Random',
    'Re_Nascence (Pystyle ver.)',
    'Realms',
    'Reimei',
    'RESSiSTANCE',
    'Retribution',
    'RIPPER',
    'Rrhar\'il',
    'Rubbish Sorting',
    'S.A.T.E.L.L.I.T.E.',
    'Sein',
    'Shadow',
    'SIGMA',
    'Snow Desert',
    'Sparkle New Life',
    'Spasmodic',
    'Speed Up!',
    'Starduster',
    #'Stasis',
    'Sultan Rage',
    '-SURREALISM-',
    'Temporal Shifting',
    'The Chariot ~REVIIVAL~',
    'The Mountain Eater',
    'Time To Night Sky (feat. Li Yu Jin)',
    'Träne',
    'Triumph & Regret',
    'Trojan',
    'Unorthodox Thoughts',
    'Upshift',
    'volcanic',
    'WATER',
    'Wavetapper',
    'Winter↑cube↓',
    'With You',
    'XING',
    'You are the Miserable',
    'Ποσειδών',
    'ρars/ey']

higher_to_lower = {
    'A':'a',
    'B':'b',
    'C':'c',
    'D':'d',
    'E':'e',
    'F':'f',
    'G':'g',
    'H':'h',
    'I':'i',
    'J':'j',
    'K':'k',
    'L':'l',
    'M':'m',
    'N':'n',
    'O':'o',
    'P':'p',
    'Q':'q',
    'R':'r',
    'S':'s',
    'T':'t',
    'U':'u',
    'V':'v',
    'W':'w',
    'X':'x',
    'Y':'y',
    'Z':'z'}


letters = {
    ' ': 486 * 3,
    '!': 23,
    '#': 1,
    '&': 2,
    "'": 15,
    '(': 27,
    ')': 27,
    '*': 3,
    '+': 3,
    ',': 7,
    '-': 30,
    '.': 35,
    '/': 4,
    '0': 9,
    '1': 7,
    '2': 3,
    '3': 2,
    '4': 2,
    '6': 1,
    '7': 2,
    '9': 5,
    ':': 3,
    ';': 1,
    '<': 1,
    '?': 1,
    '[': 3,
    ']': 3,
    '_': 2,
    'a': 536,
    'b': 89,
    'c': 213,
    'd': 194,
    'e': 649,
    'f': 97,
    'g': 129,
    'h': 171,
    'i': 444,
    'j': 10,
    'k': 78,
    'l': 324,
    'm': 188,
    'n': 351,
    'o': 410,
    'p': 111,
    'q': 10,
    'r': 459,
    's': 349,
    't': 378,
    'u': 175,
    'v': 86,
    'w': 65,
    'x': 40,
    'y': 112,
    'z': 24,
    '|': 3,
    '~': 6,
    'Ä': 2,
    'à': 1,
    'ä': 1,
    'é': 1,
    'ö': 2,
    '÷': 1,
    'ú': 1,
    'ū': 1,
    'Δ': 1,
    'Π': 1,
    'Σ': 2,
    'έ': 1,
    'α': 1,
    'β': 1,
    'γ': 1,
    'δ': 2,
    'ε': 1,
    'ι': 1,
    'κ': 1,
    'μ': 1,
    'ν': 1,
    'ο': 2,
    'ρ': 1,
    'σ': 1,
    'ω': 1,
    'ό': 1,
    'ώ': 1,
    'Я': 1,
    '†': 3,
    '↑': 1,
    '↓': 1,
    '√': 1,
    '♪': 1,
    '：': 1}

song_difficulty = [101, 29, 239, 35, 211, 318, 10, 10, 10, 266, 202, 10, 10, 10, 226, 115, 95, 240, 203, 133, 110, 68, 300, 53, 253, 10, 54, 135, 164, 228, 145, 10, 136, 205, 308, 328, 185, 196, 193, 213, 10, 222, 62, 254, 326, 193, 190, 10, 10, 10, 10, 64, 10, 231, 29, 333, 211, 177, 59, 326, 10, 63, 10, 257, 10, 159, 265, 138, 17, 162, 196, 124, 49, 266, 235, 10, 314, 10, 155, 148, 133, 256, 162, 10, 10, 172, 311, 10, 10, 136, 68, 10, 103, 226, 10, 10, 10, 10, 10, 10, 160, 10, 34, 10, 19, 10, 147, 55, 10, 122, 10, 314, 204, 174, 210, 261, 263, 10, 93, 143, 240, 237, 76, 78, 10, 10, 208, 151, 125, 332, 10, 197, 117, 10, 10, 10, 124, 114, 159, 289, 37, 10, 131, 96, 281, 116, 10, 74, 10, 287, 248, 10, 10, 138, 277, 10, 113, 292, 10, 313, 179, 10, 10, 333, 214, 10, 10, 311, 73, 10, 50, 298, 324, 10, 342, 10, 125, 10, 10, 71, 84, 10, 177, 10, 178, 85, 55, 134, 10, 10, 295, 10, 80, 10, 12, 10, 11, 264, 334, 10, 10, 209, 221, 10, 151, 10, 247, 281, 94, 291, 66, 24, 259, 10, 317, 10, 10, 10, 145, 226, 10, 210, 342, 230, 278, 51, 155, 267, 10, 241, 10, 10, 179, 200, 285, 10, 17, 209, 151, 159, 10, 169, 10, 10, 345, 97, 118, 154, 98, 10, 119, 10, 70, 10, 138, 10, 10, 10, 10, 52, 321, 92, 10, 310, 10, 79, 315, 10, 10, 181, 236, 10, 10, 174, 288, 10, 129, 10, 10, 49, 10, 212, 10, 225, 277, 10, 10, 260, 148, 343, 10, 344, 188, 126, 158, 316, 12, 118, 234, 260, 96, 10, 144, 10, 116, 10, 237, 10, 28, 10, 88, 10, 84, 211, 216, 200, 327, 225, 21, 115, 157, 10, 147, 148, 125, 10, 32, 10, 240, 77, 129, 10, 267, 250, 25, 25, 26, 142, 10, 10, 174, 317, 121, 46, 232, 165, 162, 132, 261, 297, 10, 197, 51, 105, 159, 10, 132, 131, 178, 10, 107, 182, 10, 292, 10, 148, 140, 10, 183, 173, 232, 196, 326, 323, 10, 150, 133, 347, 217, 269, 212, 185, 27, 310, 10, 95, 157, 301, 10, 24, 157, 297, 10, 125, 10, 10, 48, 305, 174, 308, 37, 10, 189, 293, 185, 158, 197, 134, 209, 276, 241, 59, 308, 150, 167, 171, 233, 169, 10, 97, 10, 186, 10, 10, 10, 10, 45, 93, 13, 209, 168, 257, 10, 309, 319, 193, 175, 65, 10, 10, 58, 236, 175, 253, 71, 10, 124, 10, 10, 91, 46, 287, 10, 250, 217, 28, 77, 277, 214, 71, 66, 321, 328, 336, 115, 10, 221, 274, 108, 112, 101, 10, 10, 10, 10, 317, 35, 286, 10, 328, 243, 292, 142, 153, 325, 121, 10, 26, 289]    

    
song_list = song_list_arcaea + song_list_phigros


def reset_letters():
    '''
        This function prints out the 'letters' dict.
    '''
    char_dict = {}
    sorted_char_dict = {}

    for song in song_list:
        for char in song:
            if char not in char_dict:
                char_dict[char] = 1
            else:
                char_dict[char] += 1
    for key in sorted(char_dict.keys()):
        sorted_char_dict[key] = char_dict[key]
    chars = sum(sorted_char_dict.values())
    
    for key in sorted_char_dict.keys():
        if key in higher_to_lower:
            if higher_to_lower[key] in sorted_char_dict:
                sorted_char_dict[higher_to_lower[key]] += sorted_char_dict[key]
                
    for key in higher_to_lower:
        if key in sorted_char_dict:
            sorted_char_dict.pop(key)
                    
    print(sorted_char_dict)
    

def reset_length_difficulty():
    '''
        This function prints out the 'length_difficulty' dict.
    '''
    lengths = {}
    sorted_lengths = {}
    for song in song_list:
        song_length = []
        words = song.split()
        for word in words:
            song_length.append(len(word))
        song_length = tuple(song_length)
        if song_length in lengths.keys():
            lengths[song_length] += 1
        else:
            lengths[song_length] = 1
    for length in sorted(lengths.keys()):
        sorted_lengths[length] = round(lengths[length] / len(song_list) * 1000, 4)
    
    print(sorted_lengths)

    

def reset_song_difficulty():
    '''
        This function prints out the 'song_difficulty' dict.
    '''
    song_difficulty = []
    for song in song_list:
        difficulty = 0
        words = song.split()
        for word in words:
            for letter in word:
                if letter in higher_to_lower:
                    difficulty += letters[higher_to_lower[letter]]
                else:
                    difficulty += letters[letter]
        difficulty //= 10
        if difficulty <= 150:
            difficulty = 475 - difficulty
        difficulty = 500 - difficulty
        if difficulty <= 10:
            difficulty = 10
        song_difficulty.append(difficulty)

    print(song_difficulty)



def reset_all():
    '''
        If there is a change in the song_list, please use this function to reset
        all the dicts above.
    '''
    reset_letters()
    reset_length_difficulty()
    reset_song_difficulty()


